version: '2'

volumes:
  training-volume:
  ssh-keygen-volume:

services:

  # traefik reverse proxy to expose the jupyter and jenkins servers over ssl via a common hostname
  traefik:
    image: traefik:v1.7
    mem_limit: 512m
    command: --debug=True --docker --docker.watch --web --web.address=:28443 --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443' --defaultEntryPoints='http,https'
    ports:
      # Not currently serving content here
      - '8443:443'
      - '8888:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # This is a single shot container that creates a set of ssh keys per instance
  # and deploys them to a persistent volume shared between the sandbox and
  # jupyter container. By doing this, we don't need to ship keys with the image
  # or source.
  ssh-keygen:
    image: agaveplatform/jupyter-notebook:5.2-slim
    entrypoint: /bin/bash
    command: /usr/local/bin/keygen.sh
    user: jovyan
    env_file:
      - training.env
    volumes:
      - ssh-keygen-volume:/home/jovyan/.ssh
      - ./docker/ssh-keygen/keygen.sh:/usr/local/bin/keygen.sh

  jupyter:
    image: agaveplatform/jupyter-notebook:5.2-slim
    mem_limit: 2048m
    restart: on-failure
    depends_on:
      - ssh-keygen
    env_file:
      - training.env
    environment:
      - GRANT_SUDO=yes
    volumes:
      - ssh-keygen-volume:/home/jovyan/.ssh
      - training-volume:/home/jovyan/work
    labels:
      - "traefik.port=8888"
      - "traefik.protocol=http"
      - "traefik.tags=testuser,jupyter"
      - "traefik.backend=testuser-training"
      - "traefik.frontend.rule=PathPrefix:/"

  sandbox:
    image: agaveplatform/training-sandbox:2.2.27
    mem_limit: 2048m
    privileged: True
    restart: on-failure
    # This port needs to be exposed for ngrok.
    ports:
      - '10022:22'
    depends_on:
      - ssh-keygen
    env_file:
      - training.env
    environment:
      - VM_MACHINE=$$ENVIRONMENT-node-$$AGAVE_USERNAME
    volumes:
      - ssh-keygen-volume:/home/jovyan/.ssh
      - training-volume:/home/jovyan/work
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false
